name: Daily Maps Downloader (R)

on:
  schedule:
    # Запуск каждый день в 04:37 UTC (это 07:37 по Москве)
    - cron: '37 4 * * *'
  workflow_dispatch: # Кнопка для ручного запуска в интерфейсе GitHub

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешаем GitHub Actions добавлять файлы в репозиторий

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Настройка R
      uses: r-lib/actions/setup-r@v2

    - name: Запуск R-скрипта
      run: Rscript download.R

    - name: Сохранение карт в репозиторий
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add maps_archive/
        git commit -m "Авто-добавление карт за: $(date +'%Y-%m-%d')" || echo "Нет изменений"
        git push
